''' <summary>
''' Field values present in an XC2 save file.
''' </summary>
Public Enum XC2DataType
    Money
    CommonItemID
    CommonItemAmount
    RareItemID
    RareItemAmount
    LegendaryItemID
    LegendaryItemAmount
    Magic
    Rex_BattleExp
    Rex_Bravery
    Rex_Truth
    Rex_Comp
    Rex_Justice
    Rex_HPMax
    Rex_Strength
    Rex_Ether
    Rex_Dex
    Rex_Agility
    Rex_Luck
    Rex_Exp
    Rex_Skill_Points
    Rex_Total_Skill_Points
    Nia_Bravery
    Nia_Truth
    Nia_Comp
    Nia_HPMax
    Nia_Stregth
    Nia_Ether
    Nia_Dexterity
    Nia_Agility
    Nia_Luck
    Nia_Exp
    Nia_Skill_Points
    Nia_Total_Skill_Points
    Nia_Justice
    Tora_Bravery
    Tora_Truth
    Tora_Comp
    Tora_Justice
    Tora_HPMax
    Tora_Stregth
    Tora_Ether
    Tora_Dexterity
    Tora_Agility
    Tora_Luck
    Tora_Exp
    Tora_Skill_Points
    Tora_Total_Skill_Points
    Zeke_Bravery
    Zeke_Truth
    Zeke_Comp
    Zeke_Justice
    Zeke_HPMax
    Zeke_Stregth
    Zeke_Ether
    Zeke_Dexterity
    Zeke_Agility
    Zeke_Luck
    Zeke_Exp
    Zeke_Skill_Points
    Zeke_Total_Skill_Points
    Morag_Bravery
    Morag_Truth
    Morag_Comp
    Morag_Justice
    Morag_HPMax
    Morag_Stregth
    Morag_Ether
    Morag_Dexterity
    Morag_Agility
    Morag_Luck
    Morag_Exp
    Morag_Skill_Points
    Morag_Total_Skill_Points
    Vandham_Bravery
    Vandham_Truth
    Vandham_Comp
    Vandham_Justice
    Vandham_HPMax
    Vandham_Stregth
    Vandham_Ether
    Vandham_Dexterity
    Vandham_Agility
    Vandham_Luck
    Vandham_Exp
    Vandham_Skill_Points
    Vandham_Total_Skill_Points
    Pyra_Trust
    Rex_Art_Weapon_0
    Rex_Art_Weapon_1
    Rex_Art_Weapon_2
    Rex_Art_Weapon_3
    Rex_Art_Weapon_4
    Rex_Art_Weapon_5
    Rex_Art_Weapon_6
    Rex_Art_Weapon_7
    Rex_Art_Weapon_8
    Rex_Art_Weapon_9
    Rex_Art_Weapon_10
    Rex_Art_Weapon_11
    Rex_Art_Weapon_12
    Rex_Art_Weapon_13
    Rex_Art_Weapon_14
    Rex_Art_Weapon_15
    Rex_Art_Weapon_16
    Rex_Art_Weapon_17
    Rex_Art_Weapon_18
    Rex_Art_Weapon_19
    Rex_Art_Weapon_20
    Rex_Art_Weapon_21
    Rex_Art_Weapon_22
    Rex_Art_Weapon_23
    Rex_Art_Weapon_24
    Rex_Art_Weapon_25
    Rex_Art_Weapon_26
    Nia_Art_Weapon_0
    Nia_Art_Weapon_1
    Nia_Art_Weapon_2
    Nia_Art_Weapon_3
    Nia_Art_Weapon_4
    Nia_Art_Weapon_5
    Nia_Art_Weapon_6
    Nia_Art_Weapon_7
    Nia_Art_Weapon_8
    Nia_Art_Weapon_9
    Nia_Art_Weapon_10
    Nia_Art_Weapon_11
    Nia_Art_Weapon_12
    Nia_Art_Weapon_13
    Nia_Art_Weapon_14
    Nia_Art_Weapon_15
    Nia_Art_Weapon_16
    Nia_Art_Weapon_17
    Nia_Art_Weapon_18
    Nia_Art_Weapon_19
    Nia_Art_Weapon_20
    Nia_Art_Weapon_21
    Nia_Art_Weapon_22
    Nia_Art_Weapon_23
    Nia_Art_Weapon_24
    Nia_Art_Weapon_25
    Nia_Art_Weapon_26
End Enum

